---
# This role installs apache2

- name: Install apache, php, git
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - php
   - php-mysql
   - git

- name: apache2 service state
  service:
    name: apache2
    state: started
    enabled: yes
