---
# This role installs HAProxy and configures it.

- name: Download and install haproxy
  apt: name=haproxy state=latest

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
